#!/bin/bash

#fcc=ifort
fcc=gfortran

[ -e wire2nek ] && rm wire2nek ./*.o

$fcc -mcmodel=medium -std=legacy -c mxm.f math.f rdwrt.f wire2nek_single.f;
$fcc -o wire2nek wire2nek_single.o math.o mxm.o rdwrt.o;
size wire2nek
